name: "Deploy to development stack"
on:
  push:
    branches-ignore:
      - master
    branches:
      - 'feature/*'

jobs:
  deploy-individual:
    name: "Deploy individual (per-developer) stack"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo the pushing user
        run: |
          echo "$GITHUB_USERNAME"
        env:
          ENVIRONMENT: dev-${{ github.event.pusher.name }}
        shell: bash
