name: "Deploy to development stack"
on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch'

jobs:
  deploy-individual:
    name: "Deploy individual (per-developer) stack"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo the pushing user
        run: |
          echo "$ENVIRONMENT"
        env:
          ENVIRONMENT: dev-${{ github.event.pusher.name }}
        shell: bash
